"""add user locale

Revision ID: 3af90249113f
Revises: fcda54931337
Create Date: 2026-06-08 20:00:20.318717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3af90249113f'
down_revision: Union[str, None] = 'fcda54931337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
