"""add_logo_url_to_subscription

Revision ID: 3e375e180a44
Revises: 3af90249113f
Create Date: 2026-06-08 23:16:33.493804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e375e180a44'
down_revision: Union[str, None] = '01213dcc7786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'logo_url')
    # ### end Alembic commands ###
