"""add reminder settings and acknowledged_billing_date

Revision ID: 45f6eb360605
Revises: 69eab0587ff4
Create Date: 2026-06-17 18:19:43.125729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45f6eb360605'
down_revision: Union[str, None] = '69eab0587ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('acknowledged_billing_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('reminders_enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('users', sa.Column('reminder_days', sa.Integer(), server_default=sa.text('3'), nullable=False))
    op.add_column('users', sa.Column('reminder_email_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('reminder_telegram_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_bot_token', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'smtp_password')
    op.drop_column('users', 'smtp_user')
    op.drop_column('users', 'smtp_port')
    op.drop_column('users', 'smtp_host')
    op.drop_column('users', 'telegram_bot_token')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'reminder_telegram_enabled')
    op.drop_column('users', 'reminder_email_enabled')
    op.drop_column('users', 'reminder_days')
    op.drop_column('users', 'reminders_enabled')
    op.drop_column('subscriptions', 'acknowledged_billing_date')
    # ### end Alembic commands ###
