"""add auto_renew to subscriptions

Revision ID: 5e32eb486ac7
Revises: 3af90249113f
Create Date: 2026-06-08 23:10:56.810912
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e32eb486ac7'
down_revision: Union[str, None] = '3af90249113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'auto_renew')
    # ### end Alembic commands ###
